projects:
  unidesigncompassapp:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: zjom4hidifh5pn7fgf3xf4r2yq
      endpoints:
        prod: >-
          https://4tta3ouufzbs5pompud5cl3nm4.appsync-api.us-east-1.amazonaws.com/graphql